### ISSUE TITLE
Fixed for the issues with disk size and swap size

### ISSUE THREAD

**Issue by a-lang** [L1so/benchy#22]
- Fixed for multiple disks not showing correct size.
 - Fixed for non-English system can't detect the SWAP.

```bash
# Fixed for multiple disks not showing correct size.
df_output=$(df -k -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total | grep "^total")
```
```bash
# Fixed for non-english system can't detect the SWAP. 
swap_info=$(LANGUAGE=en_US.UTF-8;free | awk '/Swap/ {print $2}' | convertsize)
```

**Comment by L1so** [comment]
Thanks for the suggestion (possibly PR ?), but it doesn't work on busybox `df`. I tried to be portable as possible.
```
$ busybox df -k -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total | grep "^total"
df: invalid option -- 't'
BusyBox v1.30.1 (Ubuntu 1:1.30.1-7ubuntu3) multi-call binary.

Usage: df [-PkmhTai] [-B SIZE] [FILESYSTEM]...

Print filesystem usage statistics

        -P      POSIX output format
        -k      1024-byte blocks (default)
        -m      1M-byte blocks
        -h      Human readable (e.g. 1K 243M 2G)
        -T      Print filesystem type
        -a      Show all filesystems
        -i      Inodes
        -B SIZE Blocksize
```
The language one should be okay however, I'm gonna implement that.

**Comment by a-lang** [comment]
As far as I know the Busybox is usually used on embedded system with very limited resources so all commands in busybox don't support more features.

I can't create a PR here, maybe you can check it out , if I missed something please let me know.

I love YABS, I love your fork, if possibly I will contribute some codes to this project.

**Comment by L1so** [comment]
> As far as I know the Busybox is usually used on embedded system with very limited resources so all commands in busybox don't support more features.

IIRC Alpine Linux— configured with busybox by default (I test this on lxc container), some of regular `df` command doesn't work there. I build this script with portability in mind, so I hope to support more Linux distribution that might employ bare minimum tools.

> I love YABS, I love your fork, if possibly I will contribute some codes to this project.

Yes, please do ! I welcome any contribution, in fact it is encouraged to do so.

> I can't create a PR here, maybe you can check it out , if I missed something please let me know.

I don't think I have set up anything that prevent PR to be submitted, can you tell me what's the error message (if any) ?
