### ISSUE TITLE
curl to benchy.pw return one moment please page

### ISSUE THREAD

**Issue by danipragustia** [L1so/benchy#27]
As title said.

**Comment by L1so** [comment]
Works fine here, can you post output ? Be sure to to pass redirects on curl opt `-L`

**Comment by danipragustia** [comment]
It works now, dunno what happen but from last screenshot I got when trying `curl -Ls benchy.pw | sh` I got error
`sh: <stdin>[1]: syntax error: `newline' unexpected` and when trying curl -Ls benchy.pw | cat` I got html page which have title one moment please (cloudflare pages)
This probably just my bad IP reputation. I will trying re-open issue when error coming back.
